# Profiles are convenient for grouping dotfiles
[profiles]

# Dotfiles that are needed in any environment
[profiles.main]
	dotfiles = [ "vim", "fish", "neofetch" ]

# Only sway related
[profiles.sway]
    dotfiles = [ "sway", "waybar", "wayland" ]

# Only bspwm related
[profiles.bspwm]
    dotfiles = [ "bspwm", "sxhkd" ]    

# You can install multiple profiles like this:
# sween --link --profiles "main sway"

[dotfiles]
[dotfiles.vim]
    # sources are relative to your dotfile directory
	source = "vim"
	target = "~/.vimrc" #you can write paths like this
	hooks  = [ "echo 'export EDITOR=vim' >> ~/.bashrc" ]

# You can run sween as root
# if you use sudo then your user will be automatically found
# if you use 'su -c' or doas then you must export a SUDO_USER environment variable
# Example:
# env SUDO_USER=$USER doas sween --link --dotfiles "etc_config fish"

[dotfiles.etc_config]
    source = "some_etc_config" 
    target = "/etc/etc_config" #or like this

[dotfiles.neofetch]
    source = "neofetch"
    target = "~/.config/neofetch"
    # hooks are optional

[dotfiles.wayland]
    # source and target are also optional
    hooks  = [ "echo 'set MOZ_ENABLE_WAYLAND 1'       >> ~/.config/fish/config.fish",
               "echo 'set QT_QPA_PLATFORM    wayland' >> ~/.config/fish/config.fish",
               "echo 'set GDK_BACKEND        wayland' >> ~/.config/fish/config.fish",
               "echo 'set XDG_SESSION_TYPE   wayland' >> ~/.config/fish/config.fish" ]

[dotfiles.sway]
    source = "sway"
    target = "~/.config/sway"

[dotfiles.waybar]
    source = "waybar"
    target = "~/.config/waybar"

[dotfiles.fish]
    source = "fish"
    target = "~/.config/fish"
    hooks  = [ "echo '[ -x /bin/fish ] && SHELL=/bin/fish exec /bin/fish' >> ~/.bashrc" ]

[dotfiles.bspwm]
    source = "bspwm"
    target = "~/.config/bspwm"

[dotfiles.sxhkd]
    source = "sxhkd"
    target = "~/.config/sxhkd"
